# Generated by Django 3.1.7 on 2021-04-14 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 16, 50, 26, 681120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='c441c9ee78f193ecf78b46ebd34474851b8a26499a76cb563c1a1fe5f63ee083', max_length=64),
        ),
    ]
